Lesson 2 (end)
StasBeep/js-learning-level-two pull request #2
Opened 2021-04-25 18:58 UTC by StasBeep

Вопрос: 
1. В main.js на строке 28 создаётся новый объект класса ProductItem (const productObject = new ProductItem(product);) и передаётся один параметр: product, а в конструкторе присутствует два параметра, второй параметр - это по умолчанию параметр?
2. В main.js на строке 30 заполняется массив _allProducts, зачем это делается?

2021-04-25 23:19 UTC, Om1X requested changes

2021-04-25 23:19 UTC, Om1X commented on lesson-2/main.js
> +    this.sumPrice = 0;
убираем this.sumPrice, для этого есть метод

2021-04-25 23:19 UTC, Om1X commented on lesson-2/main.js
> +      this.sumPrice += el.price;
this.sumPrice меняем на локальную sumPrice

2021-04-25 23:19 UTC, Om1X commented on lesson-2/main.js
> +    console.log(this.sumPrice);
тут вместо консоли делаем return sumPrice

2021-05-06 15:05 UTC, StasBeep commented on lesson-2/main.js
> +    this.sumPrice = 0;
Понял

2021-05-06 15:05 UTC, StasBeep commented on lesson-2/main.js
> +      this.sumPrice += el.price;
Изменил

2021-05-06 15:07 UTC, merged